version: "3.8"

services:
  hello-express:
    image: ghcr.io/rexyrex/hello-express:${IMAGE_TAG}  # <-- replace OWNER/REPO (e.g., rexyrex/hello-express)
    container_name: hello-express
    ports:
      - "2277:3000"       # host:container
    environment:
      - NODE_ENV=production
    restart: unless-stopped
