name: build-and-deploy
on:
  push:
    branches: [ main ]

permissions:
  contents: write      # commit the .portainer.env bump to deploy branch
  packages: write      # push to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Default: Use GITHUB_TOKEN to push to GHCR (works for this repo)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # If you prefer a PAT for private packages, set a repo secret GHCR_PAT and use this instead:
      # - name: Log in to GHCR (PAT)
      #   if: ${{ false }} # set to true and comment out the block above if switching to PAT
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GHCR_PAT }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}:main

      - name: Update .portainer.env with new tag
        run: |
          echo "IMAGE_TAG=${{ github.sha }}" > .portainer.env

      - name: Commit & push deploy branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B deploy
          git add .portainer.env
          git commit -m "deploy: $GITHUB_SHA"
          git push origin deploy --force
